version: "3.8"
services:
  web:
    build: .
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
    container_name: sails
    volumes:
      - ./:/usr/src/app
    command: "npm run dev"
