version: "3.8"
services:
  web:
    build: .
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://root@db:3306/scalingo_database
    container_name: sails
    volumes:
      - ./:/usr/src/app
    command: "npm run dev"
  db:
    image: mysql:5.7
    restart: always
    # MYSQL_URL SETUP
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "scalingo_database"
    container_name: sails-mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - ./_docker/mysql:/var/lib/mysql
